apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"flink.apache.org/v1beta1","kind":"FlinkDeployment","metadata":{"annotations":{},"name":"gmk-to-bq-wordcount-baseline","namespace":"default"},"spec":{"flinkConfiguration":{"rest.flamegraph.enabled":"true","taskmanager.numberOfTaskSlots":"1"},"flinkVersion":"v1_19","image":"us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/flink-examples-gcp:bq-6","job":{"args":["--brokers","bootstrap.gmf-load-test-clstr.us-central1.managedkafka.managed-flink-shared-dev.cloud.goog:9092","--gmk-username","clairemccarthy-srvc-accnt@managed-flink-shared-dev.iam.gserviceaccount.com","--kafka-topic","load-test-topic","--project-id","managed-flink-shared-dev","--dataset-name","test_ds","--table-name","test_table","--bq-sink-parallelism","10"],"entryClass":"flink.connector.gcp.GMKToBQWordCount","jarURI":"local:///opt/flink/usrlib/flink-examples-gcp-0.0.jar","parallelism":1,"upgradeMode":"stateless"},"jobManager":{"podTemplate":{"apiVersion":"v1","kind":"Pod","metadata":{"name":"pod-template"},"spec":{"containers":[{"env":[{"name":"GMK_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"gmk-sasl-plain-login"}}}],"name":"flink-main-container"}],"serviceAccount":"flink"}},"resource":{"cpu":1,"memory":"4096m"}},"serviceAccount":"flink","taskManager":{"resource":{"cpu":1,"memory":"4096m"}}}}
  creationTimestamp: "2024-05-03T16:04:13Z"
  finalizers:
  - flinkdeployments.flink.apache.org/finalizer
  generation: 4
  name: gmk-to-bq-wordcount-baseline
  namespace: default
  resourceVersion: "4552595"
  uid: 376c2473-a0c7-4e5b-a91c-6b4743ee22ee
spec:
  flinkConfiguration:
    rest.flamegraph.enabled: "true"
    taskmanager.numberOfTaskSlots: "1"
  flinkVersion: v1_19
  image: us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/flink-examples-gcp:bq-6
  job:
    args:
    - --brokers
    - bootstrap.gmf-load-test-clstr.us-central1.managedkafka.managed-flink-shared-dev.cloud.goog:9092
    - --gmk-username
    - clairemccarthy-srvc-accnt@managed-flink-shared-dev.iam.gserviceaccount.com
    - --kafka-topic
    - load-test-topic
    - --project-id
    - managed-flink-shared-dev
    - --dataset-name
    - test_ds
    - --table-name
    - test_table
    - --bq-sink-parallelism
    - "10"
    entryClass: flink.connector.gcp.GMKToBQWordCount
    jarURI: local:///opt/flink/usrlib/flink-examples-gcp-0.0.jar
    parallelism: 1
    state: running
    upgradeMode: stateless
  jobManager:
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: pod-template
      spec:
        containers:
        - env:
          - name: GMK_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: gmk-sasl-plain-login
          name: flink-main-container
        serviceAccount: flink
    replicas: 1
    resource:
      cpu: 1
      memory: 4096m
  serviceAccount: flink
  taskManager:
    resource:
      cpu: 1
      memory: 4096m
status:
  clusterInfo:
    flink-revision: eaffd22 @ 2024-03-06T15:18:44+01:00
    flink-version: 1.19.0
    total-cpu: "1.0"
    total-memory: "4294967296"
  jobManagerDeploymentStatus: READY
  jobStatus:
    checkpointInfo:
      lastPeriodicCheckpointTimestamp: 0
    jobId: ae683fe03d4ec2c5a7d2ac336e6958a2
    jobName: gmk-to-bq-wordcount-baseline
    savepointInfo:
      lastPeriodicSavepointTimestamp: 0
      savepointHistory: []
    startTime: "1714752843610"
    state: CREATED
    updateTime: "1714752854739"
  lifecycleState: DEPLOYED
  observedGeneration: 4
  reconciliationStatus:
    lastReconciledSpec: '{"spec":{"job":{"jarURI":"local:///opt/flink/usrlib/flink-examples-gcp-0.0.jar","parallelism":1,"entryClass":"flink.connector.gcp.GMKToBQWordCount","args":["--brokers","bootstrap.gmf-load-test-clstr.us-central1.managedkafka.managed-flink-shared-dev.cloud.goog:9092","--gmk-username","clairemccarthy-srvc-accnt@managed-flink-shared-dev.iam.gserviceaccount.com","--kafka-topic","load-test-topic","--project-id","managed-flink-shared-dev","--dataset-name","test_ds","--table-name","test_table","--bq-sink-parallelism","10"],"state":"running","savepointTriggerNonce":null,"initialSavepointPath":null,"checkpointTriggerNonce":null,"upgradeMode":"stateless","allowNonRestoredState":null,"savepointRedeployNonce":null},"restartNonce":null,"flinkConfiguration":{"rest.flamegraph.enabled":"true","taskmanager.numberOfTaskSlots":"1"},"image":"us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/flink-examples-gcp:bq-6","imagePullPolicy":null,"serviceAccount":"flink","flinkVersion":"v1_19","ingress":null,"podTemplate":null,"jobManager":{"resource":{"cpu":1.0,"memory":"4096m","ephemeralStorage":null},"replicas":1,"podTemplate":{"metadata":{"name":"pod-template"},"spec":{"containers":[{"env":[{"name":"GMK_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"gmk-sasl-plain-login"}}}],"name":"flink-main-container"}],"serviceAccount":"flink"}}},"taskManager":{"resource":{"cpu":1.0,"memory":"4096m","ephemeralStorage":null},"replicas":null,"podTemplate":null},"logConfiguration":null,"mode":null},"resource_metadata":{"apiVersion":"flink.apache.org/v1beta1","metadata":{"generation":4},"firstDeployment":false}}'
    reconciliationTimestamp: 1714752813880
    state: DEPLOYED
  taskManager:
    labelSelector: component=taskmanager,app=gmk-to-bq-wordcount-baseline
    replicas: 1
