apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: bq-table-api
spec:
  image: us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/bq-table-api:10
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "4096m"
      cpu: 1
  taskManager:
    resource:
      memory: "4096m"
      cpu: 1
  job:
    entryClass: flink.connector.gcp.BQTableAPI
    jarURI: local:///opt/flink/usrlib/gmf-examples.jar
    args: [] 
    parallelism: 1
    upgradeMode: stateless
