apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: gcs-to-gcs-table-api
spec:
  image: us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/gcs-table-api:latest
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "4096m"
      cpu: 1
  taskManager:
    resource:
      memory: "4096m"
      cpu: 1
  job:
    entryClass: flink.connector.gcp.GCStoGCSTableApi
    jarURI: local:///opt/flink/usrlib/gmf-examples.jar
    args: [ 
      "--input", "gs://<your-source-bucket>",
      "--output", "gs://<your-sink-bucket>",
      "--checkpoint", "gs://<your-checkpoint-bucket>" 
      ] 
    parallelism: 1
    upgradeMode: stateless
