# To run this, from inside flink-examples-gcp:
#   mvn clean package -DskipTests -Denforcer.skip=true -Dcheckstyle.skip -U
#   docker build ./ -t us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/gmk-load-gen:latest
#   docker push us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/gmk-load-gen:latest
#   kubectl apply -f gmk-load-gen.yaml
#
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: gmk-load-gen
spec:
  image: us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/gmk-load-gen:latest2
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
    taskmanager.memory.framework.heap.size: "4096m"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "32768m"
      cpu: 8
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: pod-template
      spec:
        serviceAccount: flink
        containers:
          - name: flink-main-container
            env:
            - name: GMK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gmk-sasl-plain-login
                  key: password
  taskManager:
    resource:
      memory: "32768m"
      cpu: 8
  job:
    entryClass: flink.connector.gcp.GMKLoadGenerator
    jarURI: local:///opt/flink/usrlib/gmf-examples.jar
    # Replace these with your values:
    args: ["--brokers",  "bootstrap.gmf-load-test-clstr.us-central1.managedkafka.managed-flink-shared-dev.cloud.goog:9092",
          "--gmk-username", "clairemccarthy-srvc-accnt@managed-flink-shared-dev.iam.gserviceaccount.com",
          "--kafka-topic", "load-test-topic"]
    parallelism: 1
    upgradeMode: stateless