apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: gmk-to-gmk-table-api
spec:
  image: us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/gmk-table-api:latest
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "4096m"
      cpu: 1
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: pod-template
      spec:
        serviceAccount: flink
  taskManager:
    resource:
      memory: "4096m"
      cpu: 1
  job:
    entryClass: flink.connector.gcp.GMKToGMKTableApi
    jarURI: local:///opt/flink/usrlib/gmf-examples.jar
    # Replace these with your values:
    args: ["--brokers", "bootstrap.<gmk-cluster-name>.us-central1.managedkafka-<env>.<project-name>.cloud.goog:9092",
          "--gmk-username", "<service-account-name>@<project-name>.iam.gserviceaccount.com",
          "--kafka-topic", "my-topic",
          "--project-id", "<project-name>",
          "--kafka-sink-topic", "sink-topic",
          "--oauth", "true"]
    parallelism: 5
    upgradeMode: stateless