apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"flink.apache.org/v1beta1","kind":"FlinkDeployment","metadata":{"annotations":{},"name":"gmk-to-bq-wordcount-load-test","namespace":"default"},"spec":{"flinkConfiguration":{"rest.flamegraph.enabled":"true","taskmanager.numberOfTaskSlots":"1"},"flinkVersion":"v1_19","image":"us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/flink-examples-gcp:serializer-1","job":{"args":["--brokers","bootstrap.gmf-load-test-clstr.us-central1.managedkafka.managed-flink-shared-dev.cloud.goog:9092","--gmk-username","clairemccarthy-srvc-accnt@managed-flink-shared-dev.iam.gserviceaccount.com","--kafka-topic","load-test-topic","--project-id","managed-flink-shared-dev","--dataset-name","test_ds","--table-name","test_table_not_nullable","--bq-sink-parallelism","10"],"entryClass":"flink.connector.gcp.GMKToBQWordCount","jarURI":"local:///opt/flink/usrlib/gmf-examples.jar","parallelism":1,"upgradeMode":"stateless"},"jobManager":{"podTemplate":{"apiVersion":"v1","kind":"Pod","metadata":{"name":"pod-template"},"spec":{"containers":[{"env":[{"name":"GMK_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"gmk-sasl-plain-login"}}}],"name":"flink-main-container"}],"serviceAccount":"flink"}},"resource":{"cpu":1,"memory":"4096m"}},"serviceAccount":"flink","taskManager":{"resource":{"cpu":1,"memory":"4096m"}}}}
  creationTimestamp: "2024-05-03T15:28:23Z"
  finalizers:
  - flinkdeployments.flink.apache.org/finalizer
  generation: 5
  name: gmk-to-bq-wordcount-load-test
  namespace: default
  resourceVersion: "4551649"
  uid: 5ceae5c9-6f9e-4def-83ef-5eaa0f8a7250
spec:
  flinkConfiguration:
    rest.flamegraph.enabled: "true"
    taskmanager.numberOfTaskSlots: "1"
  flinkVersion: v1_19
  image: us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/flink-examples-gcp:serializer-1
  job:
    args:
    - --brokers
    - bootstrap.gmf-load-test-clstr.us-central1.managedkafka.managed-flink-shared-dev.cloud.goog:9092
    - --gmk-username
    - clairemccarthy-srvc-accnt@managed-flink-shared-dev.iam.gserviceaccount.com
    - --kafka-topic
    - load-test-topic
    - --project-id
    - managed-flink-shared-dev
    - --dataset-name
    - test_ds
    - --table-name
    - test_table_not_nullable
    - --bq-sink-parallelism
    - "10"
    entryClass: flink.connector.gcp.GMKToBQWordCount
    jarURI: local:///opt/flink/usrlib/gmf-examples.jar
    parallelism: 1
    state: running
    upgradeMode: stateless
  jobManager:
    podTemplate:
      apiVersion: v1
      kind: Pod
      metadata:
        name: pod-template
      spec:
        containers:
        - env:
          - name: GMK_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: gmk-sasl-plain-login
          name: flink-main-container
        serviceAccount: flink
    replicas: 1
    resource:
      cpu: 1
      memory: 4096m
  serviceAccount: flink
  taskManager:
    resource:
      cpu: 1
      memory: 4096m
status:
  clusterInfo:
    flink-revision: eaffd22 @ 2024-03-06T15:18:44+01:00
    flink-version: 1.19.0
    total-cpu: "2.0"
    total-memory: "8589934592"
  jobManagerDeploymentStatus: READY
  jobStatus:
    checkpointInfo:
      lastPeriodicCheckpointTimestamp: 0
    jobId: 9b1fec26560543df8a947eff8b225e46
    jobName: gmk-to-bq-wordcount-load-test
    savepointInfo:
      lastPeriodicSavepointTimestamp: 0
      savepointHistory: []
    startTime: "1714752763508"
    state: RUNNING
    updateTime: "1714752797656"
  lifecycleState: STABLE
  observedGeneration: 5
  reconciliationStatus:
    lastReconciledSpec: '{"spec":{"job":{"jarURI":"local:///opt/flink/usrlib/gmf-examples.jar","parallelism":1,"entryClass":"flink.connector.gcp.GMKToBQWordCount","args":["--brokers","bootstrap.gmf-load-test-clstr.us-central1.managedkafka.managed-flink-shared-dev.cloud.goog:9092","--gmk-username","clairemccarthy-srvc-accnt@managed-flink-shared-dev.iam.gserviceaccount.com","--kafka-topic","load-test-topic","--project-id","managed-flink-shared-dev","--dataset-name","test_ds","--table-name","test_table_not_nullable","--bq-sink-parallelism","10"],"state":"running","savepointTriggerNonce":null,"initialSavepointPath":null,"checkpointTriggerNonce":null,"upgradeMode":"stateless","allowNonRestoredState":null,"savepointRedeployNonce":null},"restartNonce":null,"flinkConfiguration":{"rest.flamegraph.enabled":"true","taskmanager.numberOfTaskSlots":"1"},"image":"us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/flink-examples-gcp:serializer-1","imagePullPolicy":null,"serviceAccount":"flink","flinkVersion":"v1_19","ingress":null,"podTemplate":null,"jobManager":{"resource":{"cpu":1.0,"memory":"4096m","ephemeralStorage":null},"replicas":1,"podTemplate":{"metadata":{"name":"pod-template"},"spec":{"containers":[{"env":[{"name":"GMK_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"gmk-sasl-plain-login"}}}],"name":"flink-main-container"}],"serviceAccount":"flink"}}},"taskManager":{"resource":{"cpu":1.0,"memory":"4096m","ephemeralStorage":null},"replicas":null,"podTemplate":null},"logConfiguration":null,"mode":null},"resource_metadata":{"apiVersion":"flink.apache.org/v1beta1","metadata":{"generation":5},"firstDeployment":false}}'
    lastStableSpec: '{"spec":{"job":{"jarURI":"local:///opt/flink/usrlib/gmf-examples.jar","parallelism":1,"entryClass":"flink.connector.gcp.GMKToBQWordCount","args":["--brokers","bootstrap.gmf-load-test-clstr.us-central1.managedkafka.managed-flink-shared-dev.cloud.goog:9092","--gmk-username","clairemccarthy-srvc-accnt@managed-flink-shared-dev.iam.gserviceaccount.com","--kafka-topic","load-test-topic","--project-id","managed-flink-shared-dev","--dataset-name","test_ds","--table-name","test_table_not_nullable","--bq-sink-parallelism","10"],"state":"running","savepointTriggerNonce":null,"initialSavepointPath":null,"checkpointTriggerNonce":null,"upgradeMode":"stateless","allowNonRestoredState":null,"savepointRedeployNonce":null},"restartNonce":null,"flinkConfiguration":{"rest.flamegraph.enabled":"true","taskmanager.numberOfTaskSlots":"1"},"image":"us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/flink-examples-gcp:serializer-1","imagePullPolicy":null,"serviceAccount":"flink","flinkVersion":"v1_19","ingress":null,"podTemplate":null,"jobManager":{"resource":{"cpu":1.0,"memory":"4096m","ephemeralStorage":null},"replicas":1,"podTemplate":{"metadata":{"name":"pod-template"},"spec":{"containers":[{"env":[{"name":"GMK_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"gmk-sasl-plain-login"}}}],"name":"flink-main-container"}],"serviceAccount":"flink"}}},"taskManager":{"resource":{"cpu":1.0,"memory":"4096m","ephemeralStorage":null},"replicas":null,"podTemplate":null},"logConfiguration":null,"mode":null},"resource_metadata":{"apiVersion":"flink.apache.org/v1beta1","metadata":{"generation":5},"firstDeployment":false}}'
    reconciliationTimestamp: 1714752711244
    state: DEPLOYED
  taskManager:
    labelSelector: component=taskmanager,app=gmk-to-bq-wordcount-load-test
    replicas: 1
