apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: gcs-benchmark
spec:
  image: us-central1-docker.pkg.dev/managed-flink-shared-dev/gmf-chengedward/gcsbenchmark:latest15
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    entryClass: org.myorg.gcsbenchmark.ReadWriteTextUnbounded
    jarURI: local:///opt/flink/usrlib/gcsbenchmark-0.1.jar
    args: [ 
      "--output", "gs://chengedward-loadtest/output/" ] 
    parallelism: 1
    upgradeMode: stateless
