apiVersion: v1
kind: Pod
metadata:
  name: kafka-cli
  labels:
    purpose: kafka-cli
spec:
  containers:
  - name: kafka-cli
    image: us-central1-docker.pkg.dev/managed-flink-shared-dev/flink-connector-repo/kafka-cli:20240528
    command: ["/bin/sh"]
    args: ["-c", "./entrypoint.sh; while true; do sleep 3600; done"]
    env:
      - name: GMK_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: gmk-sasl-plain-login
  restartPolicy: OnFailure